package vista;

import controlador.ConAlmacen;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import modelo.Almacen;

//v1.0 SCN
public class JfiNewAlmacen extends javax.swing.JInternalFrame {

    public JfiNewAlmacen() {
        initComponents();
        this.setSize(new Dimension(400, 310));
        this.setTitle("Nuevo Almacen");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BtnRegistrar = new javax.swing.JButton();
        InputCodAlm = new javax.swing.JTextField();
        InputDirAlm = new javax.swing.JTextField();
        InputNomAlm = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nuevo Almacén");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 24, 388, -1));

        jLabel2.setText("Código:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 70, -1, -1));

        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 117, -1, -1));

        jLabel4.setText("Dirección:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 168, -1, -1));

        BtnRegistrar.setText("Registrar");
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 224, -1, -1));

        InputCodAlm.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        getContentPane().add(InputCodAlm, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 71, 198, -1));

        InputDirAlm.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        getContentPane().add(InputDirAlm, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 169, 198, -1));

        InputNomAlm.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        getContentPane().add(InputNomAlm, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 118, 198, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed
        Almacen almacen = new Almacen();
        ConAlmacen metodAlm = new ConAlmacen();

        //validaciones
        //no admite "-" el codigo
        if (InputCodAlm.getText().contains("-")) {
            JOptionPane.showMessageDialog(null, "El codigo no puede contener guiones");
        } else if (InputCodAlm.getText().trim().isEmpty() || InputNomAlm.getText().trim().isEmpty() || InputDirAlm.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Es necesario completar todos los campos");
        } else if(!metodAlm.conAlmacen(InputCodAlm.getText(), InputNomAlm.getText(), InputDirAlm.getText()).getCod_alm().isEmpty()){
                        JOptionPane.showMessageDialog(null, "Ya se encuentra registrado el Almacen con los siguientes datos: Nombre: " + metodAlm.conAlmacen(InputCodAlm.getText(), InputNomAlm.getText(), InputDirAlm.getText()).getNom_alm() + ". Con direccion: " + metodAlm.conAlmacen(InputCodAlm.getText(), InputNomAlm.getText(), InputDirAlm.getText()).getDir_alm());

        }else{
            almacen.setCod_alm(InputCodAlm.getText());
            almacen.setNom_alm(InputNomAlm.getText());
            almacen.setDir_alm(InputDirAlm.getText());
            if (metodAlm.InsAlmacen(almacen)) {
                JOptionPane.showMessageDialog(null, "Se registro el nuevo almacen correctamente");
                InputCodAlm.setText("");
                InputDirAlm.setText("");
                InputNomAlm.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Error al momento de guardar. Verificar");
            }
        }


    }//GEN-LAST:event_BtnRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JTextField InputCodAlm;
    private javax.swing.JTextField InputDirAlm;
    private javax.swing.JTextField InputNomAlm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
