package vista;

import controlador.ConCategoria;
import controlador.ConItem;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Categoria;
import modelo.Item;

public class JfiNewItem extends javax.swing.JInternalFrame {

    public JfiNewItem() {
        initComponents();
        this.setSize(new Dimension(400, 350));
        this.setTitle("Nuevo Item");
        cargarComboCategoria();
    }

    ;
    
        private void cargarComboCategoria() {
        ConCategoria metodCat = new ConCategoria();
        ArrayList<Categoria> listCategoria = metodCat.getListCategoria();
        ComboCatItem.removeAllItems();

        for (int i = 0; i < listCategoria.size(); i++) {
            ComboCatItem.addItem(listCategoria.get(i).getId_categoria() + "-" + listCategoria.get(i).getNom_categoria());
        }
    }

    ;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        InputCodItem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        InputNomItem = new javax.swing.JTextField();
        BtnRegistrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        InputDesItem = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ComboCatItem = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nuevo Articulo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 382, -1));

        jLabel2.setText("Codigo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        InputCodItem.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        getContentPane().add(InputCodItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 170, -1));

        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        InputNomItem.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        getContentPane().add(InputNomItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 170, -1));

        BtnRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnRegistrar.setText("Registrar");
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        jLabel4.setText("Descripción:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        InputDesItem.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        getContentPane().add(InputDesItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 170, -1));

        jLabel5.setText("Indicar categoria:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        ComboCatItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(ComboCatItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed
        Item item = new Item();
        ConItem metodItem = new ConItem();
        String[] split = ComboCatItem.getSelectedItem().toString().split("-");
        String IdCategoria = split[0];

        if (InputCodItem.getText().trim().isEmpty() || InputNomItem.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Es necesario ingresar un codigo y nombre de item");
        } else if (!metodItem.conItem(InputNomItem.getText(), IdCategoria).getNom_item().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El item ya se encuentra registrado en dicha categoria");
        } else {
            item.setId_item(InputCodItem.getText());
            item.setNom_item(InputNomItem.getText());
            item.setDes_item(InputDesItem.getText());
            item.setId_categoria(IdCategoria);
            //true
            if (metodItem.InsItem(item)) {
                JOptionPane.showMessageDialog(null, "Se registro correctamente");
                InputCodItem.setText("");
                InputDesItem.setText("");
                InputNomItem.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Error al registrar");
            }
        }

    }//GEN-LAST:event_BtnRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JComboBox<String> ComboCatItem;
    private javax.swing.JTextField InputCodItem;
    private javax.swing.JTextField InputDesItem;
    private javax.swing.JTextField InputNomItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
