package vista;

import controlador.ConProveedor;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import modelo.Proveedor;

//V1.0 SCN 
public class JfiNewProveedor extends javax.swing.JInternalFrame {

    public JfiNewProveedor() {
        initComponents();
        this.setSize(new Dimension(400, 400));
        ComboTipDoc.removeAllItems();
        ComboTipDoc.addItem("RUC");
        ComboTipDoc.addItem("Otro documento");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        InputNomProv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ComboTipDoc = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        InputNroDoc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        InputDesProv = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        InputDirProv = new javax.swing.JTextField();
        BtnRegistrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        InputTelefono = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nuevo Proveedor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 390, -1));

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        InputNomProv.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        getContentPane().add(InputNomProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 190, -1));

        jLabel3.setText("Tipo de documento:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        ComboTipDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(ComboTipDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 190, -1));

        jLabel4.setText("Nro de documento:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        InputNroDoc.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        getContentPane().add(InputNroDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 190, -1));

        jLabel5.setText("Descripción:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        InputDesProv.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        getContentPane().add(InputDesProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 190, -1));

        jLabel6.setText("Dirección:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        InputDirProv.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        getContentPane().add(InputDirProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 190, -1));

        BtnRegistrar.setText("Registrar");
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        jLabel7.setText("Telefono:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));
        getContentPane().add(InputTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 190, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed
        Proveedor prov = new Proveedor();
        ConProveedor metodProv = new ConProveedor();
        String CTipDoc = ComboTipDoc.getSelectedItem().toString();
        String tipDoc = "";

        if (CTipDoc.equals("RUC")) {
            tipDoc = "1";
        }
        if (CTipDoc.equals("Otro documento")) {
            tipDoc = "2";
        }

        if (InputNroDoc.getText().trim().isEmpty() || InputDirProv.getText().trim().isEmpty() || InputNomProv.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Es necesario colocar un nombre / direccion / nro de documento del proveedor.");
        } else if (metodProv.conProveedor("",InputNomProv.getText(), tipDoc, InputNroDoc.getText()).getNom_proveedor() != null) {
            JOptionPane.showMessageDialog(null, "El proveedor ya se encuentra registrado. Verificar");
        } else {
            prov.setNom_proveedor(InputNomProv.getText());
            prov.setTip_doc(tipDoc);
            prov.setNum_doc(InputNroDoc.getText());
            prov.setTelefono(InputTelefono.getText());
            prov.setDes_proveedor(InputDesProv.getText());
            prov.setDir_proveedor(InputDirProv.getText());

            if (metodProv.InsProveedor(prov)) {
                JOptionPane.showMessageDialog(null, "Se registro correctamente");
                InputNomProv.setText("");
                InputNroDoc.setText("");
                InputDesProv.setText("");
                InputDirProv.setText("");
                InputTelefono.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Error al momento de registrar. Verificar");
            }
        }
    }//GEN-LAST:event_BtnRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JComboBox<String> ComboTipDoc;
    private javax.swing.JTextField InputDesProv;
    private javax.swing.JTextField InputDirProv;
    private javax.swing.JTextField InputNomProv;
    private javax.swing.JTextField InputNroDoc;
    private javax.swing.JTextField InputTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
