package vista;

import controlador.ConCategoria;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import modelo.Categoria;

public class JfiNewCategoria extends javax.swing.JInternalFrame {

    //v1.0 SCN
    public JfiNewCategoria() {
        initComponents();
        this.setSize(new Dimension(400, 270));
        this.setTitle("Nueva Categoria");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        InputNomCategoria = new javax.swing.JTextField();
        InputDesCategoria = new javax.swing.JTextField();
        BtnRegistrarCat = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        InputCodigo = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nueva Categoria");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 382, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel3.setText("Descripcion:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        InputNomCategoria.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        InputNomCategoria.setSelectionColor(new java.awt.Color(1, 166, 139));
        getContentPane().add(InputNomCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 200, -1));

        InputDesCategoria.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        InputDesCategoria.setSelectionColor(new java.awt.Color(1, 166, 139));
        getContentPane().add(InputDesCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 200, -1));

        BtnRegistrarCat.setText("Registrar");
        BtnRegistrarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarCatActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegistrarCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel4.setText("Codigo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        InputCodigo.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        InputCodigo.setSelectedTextColor(new java.awt.Color(1, 166, 139));
        InputCodigo.setSelectionColor(new java.awt.Color(1, 166, 139));
        getContentPane().add(InputCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegistrarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarCatActionPerformed
        Categoria cat = new Categoria();
        ConCategoria metodCat = new ConCategoria();

        if (InputNomCategoria.getText().trim().isEmpty() || InputCodigo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Es necesario ingresar un nombre de categoria y codigo");
        } else if (!metodCat.conCategoria(InputCodigo.getText(), InputNomCategoria.getText()).getId_categoria().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ya se encuentra registrado dicha categoria. Hace referencia a la categoria con codigo y nombre: " + metodCat.conCategoria(InputCodigo.getText(), InputNomCategoria.getText()).getId_categoria() + " / " + metodCat.conCategoria(InputCodigo.getText(), InputNomCategoria.getText()).getNom_categoria());
        } else {
            cat.setNom_categoria(InputNomCategoria.getText());
            cat.setDes_categoria(InputDesCategoria.getText());
            cat.setId_categoria(InputCodigo.getText().trim());
            //true
            if (metodCat.InsCategoria(cat)) {
                JOptionPane.showMessageDialog(null, "Se registro correctamente");
            } else {
                JOptionPane.showMessageDialog(null, "Error al registrar");
            }
        }

        InputDesCategoria.setText("");
        InputNomCategoria.setText("");
        InputCodigo.setText("");
    }//GEN-LAST:event_BtnRegistrarCatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegistrarCat;
    private javax.swing.JTextField InputCodigo;
    private javax.swing.JTextField InputDesCategoria;
    private javax.swing.JTextField InputNomCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
